import { Component } from '@angular/core';

@Component({
  selector: 'app-directives',
  templateUrl: './directives.component.html',
  styleUrls: ['./directives.component.css']
})
export class DirectivesComponent {
  n:number = 10;
  flag: boolean = true;
  showTable: boolean = true;

  currDate:Date = new Date();
  //dayNumber = new Date().getDay();
  dayNumber = this.currDate.getDay();
  alpha: string = 'A';


  cars: string[] = ['Tesla', 'BMW', 'Tata', 'Honda', 'Toyata', 'Audi', 'Mercedes'];
  countryList: string[] = [
    "Afghanistan",
    "Albania",
    "Algeria",
    "American Samoa",
    "Andorra",
    "Angola",
    "Anguilla",
    "Antarctica",
    "Antigua and Barbuda",
    "Argentina",
    "Armenia",
    "Aruba",
    "Australia",
    "Austria",
    "Azerbaijan",
    "Bahamas",
    "Bahrain",
    "Bangladesh",
    "Barbados",
    "Belarus",
    "Belgium",
    "Belize",
    "Benin",
    "Bermuda",
    "Bhutan",
    "Bolivia",
    "Bosnia and Herzegovina",
    "Botswana",
    "Bouvet Island",
    "Brazil",
    "Brunei Darussalam",
    "Bulgaria",
    "Burkina Faso",
    "Burundi",
    "Cabo Verde",
    "Cambodia",
    "Cameroon",
    "Canada",
    "Cayman Islands",
    "Chad",
    "Chile",
    "China",
    "Christmas Island",
    "Cocos Islands",
    "Colombia",
    "Comoros",
    "Congo",
    "Congo",
    "Cook Islands",
    "Costa Rica",
    "Croatia",
    "Cuba",
    "Curaçao",
    "Cyprus",
    "Czechia",
    "Côte d'Ivoire",
    "Denmark",
    "Djibouti",
    "Dominica",
    "Dominican Republic",
    "Ecuador",
    "Egypt",
    "El Salvador",
    "Equatorial Guinea",
    "Eritrea",
    "Estonia",
    "Eswatini",
    "Ethiopia",
    "Falkland Islands [Malvinas]",
    "Faroe Islands",
    "Fiji",
    "Finland",
    "France",
    "French Guiana",
    "French Polynesia",
    "French Southern Territories",
    "Gabon",
    "Gambia",
    "Georgia",
    "Germany",
    "Ghana",
    "Gibraltar",
    "Greece",
    "Greenland",
    "Grenada",
    "Guadeloupe",
    "Guam",
    "Guatemala",
    "Guernsey",
    "Guinea",
    "Guinea-Bissau",
    "Guyana",
    "Haiti",
    "Holy See",
    "Honduras",
    "Hong Kong",
    "Hungary",
    "Iceland",
    "India",
    "Indonesia",
    "Iran",
    "Iraq",
    "Ireland",
    "Isle of Man",
    "Israel",
    "Italy",
    "Jamaica",
    "Japan",
    "Jersey",
    "Jordan",
    "Kazakhstan",
    "Kenya",
    "Kiribati",
    "Korea",
    "Kuwait",
    "Kyrgyzstan",
    "Latvia",
    "Lebanon",
    "Lesotho",
    "Liberia",
    "Libya",
    "Liechtenstein",
    "Lithuania",
    "Luxembourg",
    "Macao",
    "Madagascar",
    "Malawi",
    "Malaysia",
    "Maldives",
    "Mali",
    "Malta",
    "Marshall Islands",
    "Martinique",
    "Mauritania",
    "Mauritius",
    "Mayotte",
    "Mexico",
    "Micronesia",
    "Moldova",
    "Monaco",
    "Mongolia",
    "Montenegro",
    "Montserrat",
    "Morocco",
    "Mozambique",
    "Myanmar",
    "Namibia",
    "Nauru",
    "Nepal",
    "Netherlands",
    "New Caledonia",
    "New Zealand",
    "Nicaragua",
    "Niger",
    "Nigeria",
    "Niue",
    "Norfolk Island",
    "Northern Mariana Islands",
    "Norway",
    "Oman",
    "Pakistan",
    "Palau",
    "Palestine, State of",
    "Panama",
    "Papua New Guinea",
    "Paraguay",
    "Peru",
    "Philippines",
    "Pitcairn",
    "Poland",
    "Portugal",
    "Puerto Rico",
    "Qatar",
    "Republic of North Macedonia",
    "Romania",
    "Russian Federation",
    "Rwanda",
    "Réunion",
    "Saint Barthélemy",
    "Saint Kitts and Nevis",
    "Saint Lucia",
    "Saint Martin (French part)",
    "Saint Pierre and Miquelon",
    "Samoa",
    "San Marino",
    "Sao Tome and Principe",
    "Saudi Arabia",
    "Senegal",
    "Serbia",
    "Seychelles",
    "Sierra Leone",
    "Singapore",
    "Sint Maarten (Dutch part)",
    "Slovakia",
    "Slovenia",
    "Solomon Islands",
    "Somalia",
    "South Africa",
    "South Sudan",
    "Spain",
    "Sri Lanka",
    "Sudan",
    "Suriname",
    "Svalbard and Jan Mayen",
    "Sweden",
    "Switzerland",
    "Syrian Arab Republic",
    "Taiwan",
    "Tajikistan",
    "Tanzania",
    "Thailand",
    "Timor-Leste",
    "Togo",
    "Tokelau",
    "Tonga",
    "Trinidad and Tobago",
    "Tunisia",
    "Turkey",
    "Turkmenistan",
    "Turks and Caicos Islands",
    "Tuvalu",
    "Uganda",
    "Ukraine",
    "United Arab Emirates",
    "United States of America",
    "Uruguay",
    "Uzbekistan",
    "Vanuatu",
    "Venezuela",
    "Viet Nam",
    "Virgin Islands",
    "Wallis and Futuna",
    "Western Sahara",
    "Yemen",
    "Zambia",
    "Zimbabwe",
    "Åland Islands"
  ];
  selectedCountry:string = 'India';

  usStates = [
    {"name":"Alabama","abbr":"AL"},
    {"name":"Alaska","abbr":"AK"},
    {"name":"Arizona","abbr":"AZ"},
    {"name":"Arkansas","abbr":"AR"},
    {"name":"California","abbr":"CA"},
    {"name":"Colorado","abbr":"CO"},
    {"name":"Connecticut","abbr":"CT"},
    {"name":"Delaware","abbr":"DE"},
    {"name":"Florida","abbr":"FL"},
    {"name":"Georgia","abbr":"GA"},
    {"name":"Hawaii","abbr":"HI"},
    {"name":"Idaho","abbr":"ID"},
    {"name":"Illinois","abbr":"IL"},
    {"name":"Indiana","abbr":"IN"},
    {"name":"Iowa","abbr":"IA"},
    {"name":"Kansas","abbr":"KS"},
    {"name":"Kentucky","abbr":"KY"},
    {"name":"Louisiana","abbr":"LA"},
    {"name":"Maine","abbr":"ME"},
    {"name":"Maryland","abbr":"MD"},
    {"name":"Massachusetts","abbr":"MA"},
    {"name":"Michigan","abbr":"MI"},
    {"name":"Minnesota","abbr":"MN"},
    {"name":"Mississippi","abbr":"MS"},
    {"name":"Missouri","abbr":"MO"},
    {"name":"Montana","abbr":"MT"},
    {"name":"Nebraska","abbr":"NE"},
    {"name":"Nevada","abbr":"NV"},
    {"name":"New Hampshire","abbr":"NH"},
    {"name":"New Jersey","abbr":"NJ"},
    {"name":"New Mexico","abbr":"NM"},
    {"name":"New York","abbr":"NY"},
    {"name":"North Carolina","abbr":"NC"},
    {"name":"North Dakota","abbr":"ND"},
    {"name":"Ohio","abbr":"OH"},
    {"name":"Oklahoma","abbr":"OK"},
    {"name":"Oregon","abbr":"OR"},
    {"name":"Pennsylvania","abbr":"PA"},
    {"name":"Rhode Island","abbr":"RI"},
    {"name":"South Carolina","abbr":"SC"},
    {"name":"South Dakota","abbr":"SD"},
    {"name":"Tennessee","abbr":"TN"},
    {"name":"Texas","abbr":"TX"},
    {"name":"Utah","abbr":"UT"},
    {"name":"Vermont","abbr":"VT"},
    {"name":"Virginia","abbr":"VA"},
    {"name":"Washington","abbr":"WA"},
    {"name":"West Virginia","abbr":"WV"},
    {"name":"Wisconsin","abbr":"WI"},
    {"name":"Wyoming","abbr":"WY"}];
  selectedState:string = 'NY';
  txtState: string = '';
  selectedStates: string = 'CA,NY,NJ';

  employees = [
      {eID: 132, name: "Steve", sal: 7000, add: "Manchester"},
      {eID: 94, name: "Sachin", sal: 9000, add: "Mumbai"},
      {eID: 178, name: "Jackson", sal: 6000, add: "New York"},
  ];
  updateEmp(){
    this.employees = [
      {eID: 132, name: "Steve", sal: 7000, add: "Manchester"},
      {eID: 94, name: "Sachin", sal: 9500, add: "Mumbai"},
      {eID: 178, name: "Jackson", sal: 6000, add: "New York"},
      {eID: 178, name: "Jennifer", sal: 7500, add: "Zurich"},
    ];
  }
  trackByEmp(emp:any){
    return emp.eID;
  }
}
